<a href="https://colab.research.google.com/github/Vansh17555555/Python_Libraries/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
addres

In [ ]:
!cat /proc/meminfo


MemTotal:       13294208 kB
MemFree:         9712120 kB
MemAvailable:   12405476 kB
Buffers:           61804 kB
Cached:          2825688 kB
SwapCached:            0 kB
Active:           845560 kB
Inactive:        2498180 kB
Active(anon):       1012 kB
Inactive(anon):   456488 kB
Active(file):     844548 kB
Inactive(file):  2041692 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               268 kB
Writeback:             0 kB
AnonPages:        456196 kB
Mapped:           285608 kB
Shmem:              1252 kB
KReclaimable:      96144 kB
Slab:             131352 kB
SReclaimable:      96144 kB
SUnreclaim:        35208 kB
KernelStack:        4508 kB
PageTables:         7940 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6647104 kB
Committed_AS:    2009584 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        9460 kB
VmallocChunk:          0 kB
Percpu:          

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/sample_data/california_housing_test.csv')

In [ ]:
 df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [ ]:
print("machine learning")

machine learning


In [ ]:
!ls

sample_data


Numpu -Numerical Python
Advantages of Numpy Arrays:
1.Allows several Mathematical Operations
2. Faster operations

In [ ]:
!pip install numpy


In [ ]:
import numpy as np

Lisr vs Numpy-Time Take


In [ ]:
 from time import process_time

Time taken by a list


In [ ]:
python_list=[i for i in range(10000) ]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0013394059999995989


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0014066869999993514


Numpy Arrays

In [ ]:
# list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating a 1d array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Place holders


In [ ]:
#create a numpy array of zeros
x=np.zeros((4,5))
print(x)

In [ ]:
#create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of a particular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity matrix
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.00746428 0.9670146  0.62997504 0.5621108 ]
 [0.4314067  0.130716   0.64770022 0.9551455 ]
 [0.60529011 0.83387162 0.76040186 0.81991888]]


In [ ]:
#random integers instead of just between 0 and 1
c=np.random.randint(10,100,(3,4))
print(c)

[[25 24 90 14]
 [78 69 42 65]
 [13 30 87 96]]


In [ ]:
# array of evenly space values
d=np.linspace(10,30,9)
print(d)

[10.  12.5 15.  17.5 20.  22.5 25.  27.5 30. ]


In [ ]:
# array of evenly spaced values --> specify the step
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#converting a list to a numpy array
list2=[10,20,20,20,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analyzing a numpy array

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[18 70 52 43 59]
 [26 30 80 25 49]
 [18 50 66 27 73]
 [84 21 46 15 63]
 [67 47 17 85 25]]


In [ ]:
print(c.shape)

(5, 5)


In [ ]:
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
#checking data type of values
print(c.dtype)


int64


MatheMatical operations on a np array


In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)


[[1 3 8]
 [7 1 7]
 [4 1 3]]
[[18 17 11]
 [11 10 12]
 [19 18 11]]


In [ ]:
print(a+b)

[[19 20 19]
 [18 11 19]
 [23 19 14]]


In [ ]:
print(a-b)
print(a*b)
print(a/b)

[[-17 -14  -3]
 [ -4  -9  -5]
 [-15 -17  -8]]
[[18 51 88]
 [77 10 84]
 [76 18 33]]
[[0.05555556 0.17647059 0.72727273]
 [0.63636364 0.1        0.58333333]
 [0.21052632 0.05555556 0.27272727]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))

[[19 20 19]
 [18 11 19]
 [23 19 14]]
[[-17 -14  -3]
 [ -4  -9  -5]
 [-15 -17  -8]]


Array Manipulation


In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 0 2]
 [4 6 7]]
(2, 3)


In [ ]:
#transpose
trans=np.transpose(array)
print(trans)

[[1 4]
 [0 6]
 [2 7]]


In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 1 3]
 [9 3 5]]
(2, 3)


In [ ]:
trans=array.T
print(trans)
print(trans.shape)

[[0 9]
 [1 3]
 [3 5]]
(3, 2)


In [ ]:
#resahping an array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 4 0]
 [1 7 9]]
(2, 3)


In [ ]:
b=a.reshape(3,2)
print(b)

[[3 4]
 [0 1]
 [7 9]]
